### ISSUE TITLE
Failed to compile: "‘__lzcnt_u32’ was not declared in this scope"

### ISSUE THREAD

**Issue by lacc97** [Joshua-Ashton/d9vk#278]
D9VK doesn't compile on GCC 9.1.0 with the `-mbmi` flag.

The issue is with `util/util_bit.h`:
```
util/util_bit.h: In function ‘uint32_t dxvk::bit::lzcnt(uint32_t)’:
util/util_bit.h:74:12: error: ‘__lzcnt_u32’ was not declared in this scope; did you mean ‘__tzcnt_u32’?
   74 |     return __lzcnt_u32(n);
      |            ^~~~~~~~~~~
      |            __tzcnt_u32
```

The specific code snippet is:
```c++
inline uint32_t lzcnt(uint32_t n) {
  #if defined(_MSC_VER)
    return _lzcnt_u32(n);
  #elif defined(__BMI__)
    return __lzcnt_u32(n);
  #elif defined(__GNUC__)
    ...
```

Skimming though the [GCC source](https://github.com/gcc-mirror/gcc/blob/master/gcc/config/i386/lzcntintrin.h), it seems the `_lzcnt_u32` (only one underscore) intrinsic is defined if `__LZCNT__` is defined. So the solution is probably to substitute `__LZCNT__` for `__BMI__` in the conditional and correct the number of leading underscores:
```c++
inline uint32_t lzcnt(uint32_t n) {
  #if defined(_MSC_VER) || defined(__LZCNT__)
    return _lzcnt_u32(n);
  #elif defined(__GNUC__)
    ...
```
